### PR TITLE
Add balena utilities

### PR DESCRIPTION
**Pull request by critzo**
This PR adds a script to provision a new Murakami device in a Balena Cloud fleet.
Empty directories are also added:
* `utilities/balenaDeviceConfigs` - where the script saves device configuration files
* `configs` - intended to house general configuration files needed for different parts of Murakami, like configs for specific runners

Additions to .gitignore ensure downloaded .img files from Balena are not added to a commit, and .json device configuration files in the directories above.

@robertodauria PTAL?

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/murakami/94)

### CODE REVIEW

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/murakami/94)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo)

___
*[utilities/setup_balena_device.sh, line 15 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0pvco2lrUQ7kiB3YL:-Mi0pvcpEaPGjE6FycwI:bd6wyj) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L15)):*
> ```Shell
> 
> ## register new device
> uuid=$(balena device register $balenaFleet | awk '{ print $4 }')
> ```

What happens if the balena client isn't authenticated? Shouldn't this script terminate early?
___
*[utilities/setup_balena_device.sh, line 36 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0qSWH-PPGUGLPjYo1:-Mi0qSWH-PPGUGLPjYo2:bsvsm1a) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L36)):*
> ```
> 2.38.3+rev3
> ```

If this is the image's version I would recommend putting it into a variable.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 15 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0pvco2lrUQ7kiB3YL:-Mi0x_6L83_2pal11yAb:b-p7j3oz) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L15)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

What happens if the balena client isn't authenticated? Shouldn't this script terminate early?
</blockquote></details>

I'm assuming that the client has already authenticated, but the first prompt could be to check for the installation of balena-cli, and then for authentication. I could see some other interactive things that could be added too.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 36 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0qSWH-PPGUGLPjYo1:-Mi0y0iB5vGeVd6E3YfZ:bssn5ja) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L36)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

> ```
> 2.38.3+rev3
> ```

If this is the image's version I would recommend putting it into a variable.
</blockquote></details>

I'd like to pull that from the balena API and store it as a variable, but still looking at the API. Another one that could be made into a variable could be the device type.

**Review by robertodauria — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/murakami/94)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo and @robertodauria)

___
*[utilities/setup_balena_device.sh, line 36 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0qSWH-PPGUGLPjYo1:-Mi0yPzD7ABL880AWTqe:bhn28zn) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L36)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I'd like to pull that from the balena API and store it as a variable, but still looking at the API. Another one that could be made into a variable could be the device type.
</blockquote></details>

I wasn't thinking of getting it dynamically from the API (even if it's a nice long-term solution!), just giving it a name so the next person reading this script can understand what it is more easily.

Without prior knowledge, I don't know if that's the device's version, the config's version, or the base Balena image's version.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 36 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0qSWH-PPGUGLPjYo1:-Mi1DiIG2Kcq13NrSlou:b-dkbkyx) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L36)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I wasn't thinking of getting it dynamically from the API (even if it's a nice long-term solution!), just giving it a name so the next person reading this script can understand what it is more easily.

Without prior knowledge, I don't know if that's the device's version, the config's version, or the base Balena image's version.
</blockquote></details>

Ah, I see. Some more informative code comments could clarify what's happening.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 15 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0pvco2lrUQ7kiB3YL:-Mi2xSEu2mUpNBUsFIcu:b-behyew) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L15)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

I'm assuming that the client has already authenticated, but the first prompt could be to check for the installation of balena-cli, and then for authentication. I could see some other interactive things that could be added too.
</blockquote></details>

There is now a check for 1) is balena-cli installed and 2) is the user logged in. Script stops if either of these is not the case.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 36 at r1](https://reviewable.io/reviews/m-lab/murakami/94#-Mi0qSWH-PPGUGLPjYo1:-Mi2xemZ6exZmrHJNfmQ:bmhvxrn) ([raw file](https://github.com/m-lab/murakami/blob/63fa1dcad1873802be5c681d2bebc9071fc60a57/utilities/setup_balena_device.sh#L36)):*
<details><summary><i>Previously, critzo wrote…</i></summary><blockquote>

Ah, I see. Some more informative code comments could clarify what's happening.
</blockquote></details>

I added a code comment that lets users know what this version string means. I hope to auto-detect that in the future.
Also I added an API call to get the device type for the fleet automatically, and a prompt to ask the user whether they need to download the latest release image for the fleet or not.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 58 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi2y3zg6CrJPy3ReTmu:-Mi2y3zg6CrJPy3ReTmv:b29xah8) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L58)):*
> ```Shell
> 	
> 	availableDevice=$(balena util available-drives)
> ```

Also found this handy API call that checks to see if an SD card is inserted in the host system. If it is, then the final instructions suggest it as a target. In the future there could possibly be a user prompt to flash the card as well.

**Comment by critzo** [comment]
@robertodauria Made your requested changes and added some others.

**Review by robertodauria — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/murakami/94)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @critzo and @robertodauria)

___
*[utilities/setup_balena_device.sh, line 13 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5ld41A9HofYNWgi72:-Mi5ld41A9HofYNWgi73:bn7h9et) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L13)):*
> ```Shell
> echo "balena is installed at: ${balenaInstalled}"
> 
> if [ -z ${balenaInstalled} ]; then
> ```

Could you please add a message for the user to install the Balena CLI in this case?
___
*[utilities/setup_balena_device.sh, line 18 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5lj5h3rG8mewuHNrj:-Mi5lj5h3rG8mewuHNrk:b-g46s77) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L18)):*
> ```Shell
> 
> balenaLoggedIn=$(balena fleets)
> if [ -z "${balenaLoggedIn}" ]; then
> ```


If there are no fleets this will still succeed since the table's header is printed anyway. I think it's OK as long as commands that rely on a certain fleet existing are checked for errors further down the script.

In general, it's better to check for exit codes rather than relying on the output of the CLI to remain stable. e.g.  this checks that the exit code of `balena fleets` is non-zero (true if the user hasn't logged in, or in case of network errors, etc.)

```
if ! balena fleets; then
  exit 1
fi
```
___
*[utilities/setup_balena_device.sh, line 20 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5q8qZ6v1tX4eghNRp:-Mi5q8qZ6v1tX4eghNRq:b-qsdjo4) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L20)):*
> ```Shell
> if [ -z "${balenaLoggedIn}" ]; then
> 	exit 1
> else
> ```

You can remove this `else` and unindent the following lines, since we've already exited in case of errors.
___
*[utilities/setup_balena_device.sh, line 27 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5pUN5BWdZfRMf9zqF:-Mi5pUN5BWdZfRMf9zqG:b-paz0us) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L27)):*
> ```Shell
> 
> 	## register new device
> 	uuid=$(balena device register $balenaFleet | awk '{ print $4 }')
> ```

If this can fail if `$balenaFleet` does not exist, please check for the exit code. You'll need to split the `balena device register` and the `awk` commands though, as `awk` will happily process an empty line end return an exit code = 0. 

Or, in this case, you can just check that the output is non-empty.
___
*[utilities/setup_balena_device.sh, line 44 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5sCih5NfOqiDS8UGO:-Mi5sCih5NfOqiDS8UGP:b-huhp4v) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L44)):*
> ```Shell
> 
> 	# Download an SD card image
> 	balenaDeviceType=$(balena fleet murakami-demo-baltimore | grep 'DEVICE TYPE' | cut -f 1 | cut -d ":" -f2 )
> ```

Should this use the `$balenaFleet` variable as above?

Checking for non-emptiness here is probably redundant, but it makes the script more robust in case the part before changes in the future. I'll leave it up to you :)
___
*[utilities/setup_balena_device.sh, line 50 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5snigDx2B7_T7sWTb:-Mi5snigDx2B7_T7sWTc:b-qtvlc1) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L50)):*
> ```Shell
> 
> 	if [ ${downloadDeviceImage} = "Y"  ]; then
> 		balena os download $balenaDeviceType -o $balenaFleet.img --version latest
> ```

Please check that this command succeeded before proceeding.
___
*[utilities/balenaDeviceConfigs/README.md, line 0 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5tfnF5U-q5N8HkyY8:-Mi5tfnF5U-q5N8HkyY9:bc7pa5d) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/balenaDeviceConfigs/README.md#L0)):*
Nit: the standard way of adding empty folders on Git is to add a file named `.gitkeep`. I assume this README will have some content in the future (e.g. to explain why the folder exists), so I think in this case it's fine. 

A possible alternative could be creating this folder as part of the setup script since it's only used there (and only to write, so it does not need to exist beforehand).

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 13 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5ld41A9HofYNWgi72:-Mi6dnx0BpCo8hw5GB2v:b-68xmbw) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L13)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Could you please add a message for the user to install the Balena CLI in this case?
</blockquote></details>

Added in latest commit.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 18 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5lj5h3rG8mewuHNrj:-Mi6dquP9C2x35kjA_iW:b-68xmbw) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L18)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>


If there are no fleets this will still succeed since the table's header is printed anyway. I think it's OK as long as commands that rely on a certain fleet existing are checked for errors further down the script.

In general, it's better to check for exit codes rather than relying on the output of the CLI to remain stable. e.g.  this checks that the exit code of `balena fleets` is non-zero (true if the user hasn't logged in, or in case of network errors, etc.)

```
if ! balena fleets; then
  exit 1
fi
```

</blockquote></details>

Added in latest commit.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 20 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5q8qZ6v1tX4eghNRp:-Mi6dwSX46e-hRnqvfwQ:b-6eoh4c) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L20)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

You can remove this `else` and unindent the following lines, since we've already exited in case of errors.
</blockquote></details>

Removed in latest commit.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 27 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5pUN5BWdZfRMf9zqF:-Mi6e41b7IMgWdx4mnRd:b5236fx) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L27)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

If this can fail if `$balenaFleet` does not exist, please check for the exit code. You'll need to split the `balena device register` and the `awk` commands though, as `awk` will happily process an empty line end return an exit code = 0. 

Or, in this case, you can just check that the output is non-empty.
</blockquote></details>

Set script options for error handling and pipefail per your suggestion of team practice for bash.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 44 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5sCih5NfOqiDS8UGO:-Mi6eOJT12fUvXCBzPmz:b-k7ia4o) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L44)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Should this use the `$balenaFleet` variable as above?

Checking for non-emptiness here is probably redundant, but it makes the script more robust in case the part before changes in the future. I'll leave it up to you :)
</blockquote></details>

Pipefail and other error options now address this.

**Comment by critzo** [comment]
___
*[utilities/setup_balena_device.sh, line 50 at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5snigDx2B7_T7sWTb:-Mi6eSQO82QwwX1FiNru:b-ateixm) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/setup_balena_device.sh#L50)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Please check that this command succeeded before proceeding.
</blockquote></details>

Same comment re: pipefail & script options.

**Comment by critzo** [comment]
___
*[utilities/balenaDeviceConfigs/README.md, line  at r2](https://reviewable.io/reviews/m-lab/murakami/94#-Mi5tfnF5U-q5N8HkyY8:-Mi6eXh47aTyHA4V63QB:bb7cwne) ([raw file](https://github.com/m-lab/murakami/blob/75432dbae29317336c0a53557f67946ae455c6ab/utilities/balenaDeviceConfigs/README.md#L)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

Nit: the standard way of adding empty folders on Git is to add a file named `.gitkeep`. I assume this README will have some content in the future (e.g. to explain why the folder exists), so I think in this case it's fine. 

A possible alternative could be creating this folder as part of the setup script since it's only used there (and only to write, so it does not need to exist beforehand).
</blockquote></details>

ack.

**Comment by critzo** [comment]
@robertodauria Changes committed. PTAL once more?

**Review by robertodauria — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/murakami/94#-:-Mi7IJFT3y37hDZaagPc:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @critzo and @robertodauria)

**Pull request merged**
